apiVersion: v1
kind: Template
metadata:
  name: todo-app-template
objects:
  # PersistentVolumeClaim (PVC) - This part remains unchanged
  - apiVersion: v1
    kind: PersistentVolumeClaim
    metadata:
      name: todo-pvc
    spec:
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 1Gi

  # Service - No change here either
  - apiVersion: v1
    kind: Service
    metadata:
      name: todo-service
    spec:
      selector:
        app: todo-app
      ports:
        - protocol: TCP
          port: 80
          targetPort: 3333

  # DeploymentConfig - Update this part to mount the PVC correctly
  - apiVersion: apps.openshift.io/v1
    kind: DeploymentConfig
    metadata:
      name: todo-deployment
    spec:
      replicas: 1
      selector:
        app: todo-app
      template:
        metadata:
          labels:
            app: todo-app
        spec:
          containers:
            - name: todo-container
              image: todo-image  # Replace with your actual image name
              ports:
                - containerPort: 3333
              #volumeMounts:
                # Mount PVC to the backend folder where todos.db is stored
                #- mountPath: /app/backend/todos.db
                 # name: todo-storage
                  #subPath: todos.db  # Ensure the PVC mounts only the todos.db file
          #volumes:
           # - name: todo-storage
            #  persistentVolumeClaim:
             #   claimName: todo-pvc  # Reference to PVC for storage
